
server.port=8080
spring.application.name=blackjack-webflux

# Configuración de MySQL (R2DBC)
spring.r2dbc.url=r2dbc:mysql://localhost:3306/blackjackdb
spring.r2dbc.username=root
spring.r2dbc.password=iFer313.
spring.r2dbc.driver=mysql

# Configuración de MongoDB Reactivo
spring.data.mongodb.uri=mongodb://localhost:27017/blackjack

# Configuración de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
